### PR TITLE
epg updates

### PR DESCRIPTION
**Pull request by babysteps**

### CODE REVIEW

**Comment by piyushdpro** [comment]
Hi Michael
Thanks for recommendations.
Just want to ask is it merge issue because when I ran the code, I found
1. Player and EPG Programs in column rather than in row
2. Time row is missing
3. EPG is not scrollable horizontally

ezgif-1-418f098285bf

**Comment by babysteps** [comment]
interesting... it has something to do with the redirect from home to channels.  try going here:
http://localhost:3000/channels

Where are you doing that redirect?

**Comment by piyushdpro** [comment]
Yeah, redirect from http://localhost:3000/channels worked.

I was doing it from http://localhost:3000

**Comment by babysteps** [comment]
yeah, something about how it's redirecting from the homepage isn't loading the css.  i think the homepage is going to be a splash page, so this redirect won't actually happen when the site is done.

**Comment by babysteps** [comment]
hey Piyush, 

I sent this message to Joe outlining what I did, but I don't know if he sent it to you, so I'll post it here.  Let me know if you have questions.

- It looks like you had 2 very similar style sheets, one for the index page, and another for the channel page.  These 2 files were “fighting” with each other, so i commented out the import on the index page.  all styling should be done in the channels less file now.
- The left column is now using position: sticky so that it goes up when you hit the footer, and i reworked some of the css in that column to better match what i saw in the comp.  I also swapped a handful of elements that were being individually positioned with margin, and instead put padding in the containing element to simply the css.
- I also updated the css for the mobile layout.
- I reworked the scroll listener so that it doesn’t use jquery and made some performance improvements.  updating position with transform is always preferred over top.  I was also able to remove the js for .timeElapsed by changing the css for it.
- added Math.floor to your width calculation for programs so that the widths are whole numbers.
- Reworked/Removed some unnecessary css styling
- I made it so the kebab stays inside the current program, but still need to figure out how to bring it back in for programs that are wider than the viewable space.  This is likely going to take javascript, but i wanted to give it a little more thought via CSS before adding JS.

**Comment by piyushdpro** [comment]
Hi,
I have removed the bug regarding redirects. Now it's working fine

**Pull request closed without merging**
